# Generated by Django 6.0.2 on 2026-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20220217_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(max_length=100),
        ),
    ]
