# Generated by Django 6.0.2 on 2026-04-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_customer_latitude_customer_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='hired',
            field=models.BooleanField(default=True),
        ),
    ]
